# Generated by Django 3.0.8 on 2020-07-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='denuncias',
            field=models.IntegerField(default=0),
        ),
    ]
