# Generated by Django 3.1 on 2020-09-02 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_noticia_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos_noticias')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.noticia')),
            ],
        ),
    ]
